#!/bin/bash
#参数说明
#-p 指定本机公钥的位置，如不指定默认为$HOME/.ssh/id_rsa.pub
#-h 指定要连接的远程主机（必须指定）
#-a 指定是否复制本机的公钥至远程主机

#默认的公钥
pubkey=$HOME/.ssh/id_rsa.pub

#解析参数
#echo $pubkey
while getopts "h:p:a" arg #选项后面的冒号表示该选项需要参数
do
	case $arg in
		p)
			pubkey=$OPTARG
			;;
		h)
			host=$OPTARG
			;;
		a)
			if [[ ! $host ]]; then
				echo "err:need -h option"
				echo "USAGE:ska -h USER@HOST [-p LOCAL_PUBKEY_FILE]"
				exit 1
			fi
			echo "PUBKEY:"$pubkey
			echo "HOST:"$host
			read key < $pubkey
			ssh $host "echo "$key" >> ~/.ssh/authorized_keys;chmod 600 ~/.ssh/authorized_keys"
		?) #当有不认识的选项的时候arg为?
			echo "err:unkonw argument"	
			exit 1
			;;
	esac
done
if [[ ! $host ]]; then
	echo "err:need -h option"
	echo "USAGE:ska -h USER@HOST [-p LOCAL_PUBKEY_FILE]"
	exit 1
fi

ssh $host